import { TemplateRef } from '@angular/core';
import type { IDropdownOption } from '../../../interfaces/components/dropdown.interface';
import type { AppliedFilterChip, FilterChange, FilterConfigItem, FilterSelections, NormalizedFilterConfigItem } from './custom-main-pages-modal-filter.models';
import * as i0 from "@angular/core";
interface FilterState {
    searchText: string;
    selectedIdsLegacy: unknown[];
    selectionsMap: FilterSelections;
}
export declare class CustomMainPagesModalFilterContainerComponent {
    dropdownOptions: import("@angular/core").InputSignal<IDropdownOption[]>;
    dropdownSelectedValues: import("@angular/core").InputSignal<unknown[]>;
    dropdownPlaceholder: import("@angular/core").InputSignal<string>;
    searchInputPlaceholder: import("@angular/core").InputSignal<string>;
    defaultBehaviorFlag: import("@angular/core").InputSignal<boolean>;
    configs: import("@angular/core").InputSignal<FilterConfigItem[]>;
    moreConfigs: import("@angular/core").InputSignal<FilterConfigItem[]>;
    showMore: import("@angular/core").InputSignal<boolean>;
    validateNumber: import("@angular/core").InputSignal<boolean>;
    externalFiltersHasValue: import("@angular/core").InputSignal<boolean>;
    hasFiltered: import("@angular/core").InputSignal<boolean>;
    modalTitle: import("@angular/core").InputSignal<string>;
    customTemplates: import("@angular/core").InputSignal<Record<string, TemplateRef<unknown>>>;
    chipsPlacement: import("@angular/core").InputSignal<"default" | "below-header">;
    filterChange: import("@angular/core").OutputEmitterRef<FilterChange>;
    filterReset: import("@angular/core").OutputEmitterRef<boolean>;
    private readonly modalService;
    readonly appliedState: import("@angular/core").WritableSignal<FilterState>;
    readonly initialState: import("@angular/core").WritableSignal<FilterState>;
    readonly normalizedConfigs: import("@angular/core").Signal<NormalizedFilterConfigItem[]>;
    readonly hasAnyFilterValue: import("@angular/core").Signal<boolean>;
    readonly hasChangedFromInitial: import("@angular/core").Signal<boolean>;
    readonly appliedChips: import("@angular/core").Signal<AppliedFilterChip[]>;
    readonly shouldDisableReset: import("@angular/core").Signal<boolean>;
    constructor();
    openFilters(): Promise<void>;
    applyDraft(values: FilterSelections, searchText?: string): void;
    removeChip(chip: AppliedFilterChip): void;
    resetFilters(): void;
    private emitAppliedChange;
    private stateFromExternalInputs;
    private normalizeConfigs;
    private normalizeConfig;
    private hasExplicitInitialValue;
    private normalizeSelections;
    private toPayloadSelections;
    private buildChipsForConfig;
    private labelForValue;
    private syncFormBindings;
    private emptyValueFor;
    private emptyValueByType;
    private hasValue;
    private toArray;
    private selectionsEqual;
    private valuesEqual;
    private arraysEqual;
    private cloneState;
    private cloneSelections;
    private cloneValue;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomMainPagesModalFilterContainerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomMainPagesModalFilterContainerComponent, "custom-main-pages-modal-filter-container", never, { "dropdownOptions": { "alias": "dropdownOptions"; "required": false; "isSignal": true; }; "dropdownSelectedValues": { "alias": "dropdownSelectedValues"; "required": false; "isSignal": true; }; "dropdownPlaceholder": { "alias": "dropdownPlaceholder"; "required": false; "isSignal": true; }; "searchInputPlaceholder": { "alias": "searchInputPlaceholder"; "required": false; "isSignal": true; }; "defaultBehaviorFlag": { "alias": "defaultBehaviorFlag"; "required": false; "isSignal": true; }; "configs": { "alias": "configs"; "required": false; "isSignal": true; }; "moreConfigs": { "alias": "moreConfigs"; "required": false; "isSignal": true; }; "showMore": { "alias": "showMore"; "required": false; "isSignal": true; }; "validateNumber": { "alias": "validateNumber"; "required": false; "isSignal": true; }; "externalFiltersHasValue": { "alias": "externalFiltersHasValue"; "required": false; "isSignal": true; }; "hasFiltered": { "alias": "hasFiltered"; "required": false; "isSignal": true; }; "modalTitle": { "alias": "modalTitle"; "required": false; "isSignal": true; }; "customTemplates": { "alias": "customTemplates"; "required": false; "isSignal": true; }; "chipsPlacement": { "alias": "chipsPlacement"; "required": false; "isSignal": true; }; }, { "filterChange": "filterChange"; "filterReset": "filterReset"; }, never, ["[extraFilters]", "[extraFiltersMore]"], true, never>;
}
export type { AppliedFilterChip as MainPagesModalFilterChip, FilterChange as MainPagesModalFilterChange, FilterConfigItem as MainPagesModalFilterConfigItem, FilterCustomTemplateContext as MainPagesModalFilterCustomTemplateContext, FilterInputType as MainPagesModalFilterInputType, FilterSelections as MainPagesModalFilterSelections, FilterValue as MainPagesModalFilterValue, } from './custom-main-pages-modal-filter.models';
